"""empty message

Revision ID: 2037169cc5c3
Revises: None
Create Date: 2015-09-18 15:22:37.300699

"""

# revision identifiers, used by Alembic.
revision = '2037169cc5c3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
